base_url          = "http://export.arxiv.org"
endpoint_template = "http://export.arxiv.org/api/query?id_list={identifier}&max_results=1"
name              = "arxiv"
pattern           = "(?:^|https?://arxiv\\.org/(?:abs|pdf)/)(\\d{4}\\.\\d{4,5}|[a-zA-Z-]+(?:\\.[A-Z]{2})?/\\d{7})(?:\\.pdf)?$"
resource          = "paper"
source            = "arxiv"

[response_format]
strip_namespaces = true
type             = "xml"


# TODO: Could flatten out the `field_maps`?
[response_format.field_maps.title]
path = "feed/entry/title"

[response_format.field_maps.abstract]
path = "feed/entry/summary"

[response_format.field_maps.authors]
path = "feed/entry/author"

[response_format.field_maps.publication_dates]
path = "feed/entry/published"

[retrieval_data.urls]
path = "feed/entry/id"

[retrieval_data.urls.transform]
pattern     = "/abs/"
replacement = "/pdf/"
type        = "Replace"

[headers]
Accept = "application/xml"
