name = "iacr"

description = "Retriever template for getting a paper from IACR"

resource_template  = "paper"
retrieval_template = "retrieval"

base_url          = "https://eprint.iacr.org"
endpoint_template = "https://eprint.iacr.org/oai?verb=GetRecord&identifier=oai:eprint.iacr.org:{identifier}&metadataPrefix=oai_dc"
pattern           = "(?:^|https?://eprint\\.iacr\\.org/)(\\d{4}/\\d+)(?:\\.pdf)?$"
source            = "iacr"

response_format = { type = "xml", strip_namespaces = true }

[resource_mappings]
abstract          = { path = "OAI-PMH/GetRecord/record/metadata/dc/description" }
authors           = { path = "OAI-PMH/GetRecord/record/metadata/dc/creator" }
publication_dates = { path = "OAI-PMH/GetRecord/record/metadata/dc/date" }
title             = { path = "OAI-PMH/GetRecord/record/metadata/dc/title" }

[retrieval_mappings.urls]
path = "OAI-PMH/GetRecord/record/metadata/dc/identifier"
structure = { "pdf" = "https://eprint.iacr.org/{value}.pdf", "html" = "https://eprint.iacr.org/{value}" }
transforms = [
    { type = "Replace", pattern = ".*/(\\d{4}/\\d+)$", replacement = "$1" },
]

[headers]
Accept = "application/xml"
