# paper_record.toml
description = "Record configuration for academic papers"
extends     = ["paper"]
name        = "paper_record"

[item.resource]
required_fields = ["title", "authors", "publication_date", "abstract_text"]
resource_type   = "paper"

[item.state_tracking]
allow_notes       = true
progress_tracking = true
rating_system     = 5
track_access_time = true

[item.storage]
required_files     = ["pdf"]
track_checksums    = true
track_file_history = true

[item.retrieval]
access_types  = ["open", "subscription"]
track_urls    = true
url_types     = ["pdf", "html"]
verify_access = true
