description = "Configuration for a paper"
name        = "paper"

abstract_text     = { field_type = "string", required = false }
authors           = { field_type = "array", required = true, validation = { min_items = 1 } }
publication_dates = { field_type = "array", required = true, validation = { datetime = true } }
title             = { field_type = "string", required = true, validation = { min_length = 1, max_length = 500 } }
