description = "Configuration for a paper"
name        = "paper"

[abstract]
base_type = "string"
required  = false

[title]
base_type  = "string"
required   = true
validation = { min_length = 1, max_length = 500 }

[publication_dates]
base_type = "array"
items     = { base_type = "string", validation = { datetime = true } }
required  = true

[authors]
base_type  = "array"
required   = true
validation = { min_items = 1 }
[authors.items]
base_type = "object"
fields = [
    { name = "name", base_type = "string", required = true, validation = { min_length = 1 } },
    { name = "affiliation", base_type = "string", required = false },
]
