description = "Standard retrieval data template"
name        = "retrieval"

[source]
base_type = "string"
required  = false

[source_identifier]
base_type = "string"
required  = false

[urls]
base_type = "object"
fields = [
    { name = "pdf", base_type = "string", required = false },
    { name = "html", base_type = "string", required = false },
]
required = false

[doi]
base_type = "string"
required  = false

[last_checked]
base_type  = "string"
required   = false
validation = { datetime = true }

[access_type]
base_type  = "string"
required   = false
validation = { enum_values = ["open", "subscription", "institutional"] }
