description = "Base state tracking template"
name        = "state"

[read_status]
base_type  = "string"
required   = true
validation = { enum_values = ["unopened", "opened", "completed"] }

[starred]
base_type = "boolean"
default   = false
required  = true

[rating]
base_type  = "number"
required   = false
validation = { minimum = 1, maximum = 5 }

# Additional fields can be added by extending this template
