name = "storage"

description = "Base storage configuration template"

type = "storage"

[files]
base_type = "object"
required  = true

[original_filenames]
base_type = "object"
required  = true

[added_at]
base_type = "object"
required  = true
