coverage:
  precision: 2
  round: up    
  range: "40...100" 

  status:
    project:
      default:
        target: 50%   
        threshold: 5% 
    patch:
      default:
        target: 40%    
        threshold: 10% 

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false