[workspace]
allow_dirty         = false
semver_check        = true
dependencies_update = true

# Configure the order of releases
[[package]]
name    = "learner"
publish = true

[[package]]
name    = "learnerd"
publish = true
# This will make release-plz wait for learner to be published
publish_delay       = "30s"
dependencies_update = [{ name = "learner", version_template = "={{version}}" }]
