[package]
name        = "learner"
version     = "0.1.3"
edition     = "2021"
description = "A simple library for learning stuff"
authors     = ["Colin Roberts"]
repository  = "https://github.com/autoparallel/learner"
license     = "Apache-2.0"
# documentation = "https://docs.rs/learner"
readme   = "README.md"
keywords = ["learning", "research", "automation", "papers"]

[dependencies]
tokio       = { version = "1.41", features = ["full"] }
reqwest     = { version = "0.12", features = ["json"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
thiserror   = "1.0"
url         = "2.5"
regex       = "1.11"
chrono      = { version = "0.4", features = ["serde"] }
tracing     = "0.1"
quick-xml   = { version = "0.37", features = ["serialize"] }
lazy_static = "1.5.0"

[dev-dependencies]
tokio-test   = "0.4"
tracing-test = "0.2.5"
anyhow       = "1.0"
