[package]
name = "learnerd"
version = "0.1.0"
edition = "2021"
description = "A simple library for learning stuff"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
url = "2.4"
regex = "1.10"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
quick-xml = { version = "0.37", features = ["serialize"] }

[dev-dependencies]
tokio-test = "0.4"
pretty_assertions = "1.0"
