[workspace]
members = ["crates/learner", "crates/learnerd"]

[workspace.package]
edition    = "2021"
authors    = ["Colin Roberts"]
repository = "https://github.com/autoparallel/learner"
license    = "Apache-2.0"
keywords   = ["learning", "research", "automation", "papers"]

[workspace.dependencies]
tokio = { version = "1.41", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.5"
regex = "1.11"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
quick-xml = { version = "0.37", features = ["serialize"] }
lazy_static = "1.5"
clap = { version = "4.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "sqlite",
    "chrono",
    "json",
    "migrate",
] }
rusqlite = { version = "0.32", features = ["bundled", "functions", "chrono"] }
tokio-rusqlite = "0.6"
dirs = "5.0"

# Dev dependencies
tokio-test   = "0.4"
tracing-test = "0.2"
anyhow       = "1.0"
