name = "state"

description = "State tracking template"

type = "state"

[status]
base_type  = "string"
required   = true
validation = { enum_values = ["unopened", "opened", "completed"] }

[tags]
base_type = "string"
required  = true

[starred]
base_type = "boolean"
default   = false
required  = true

[rating]
base_type  = "number"
required   = false
validation = { minimum = 1, maximum = 5 }
