name = "storage"

description = "Base storage configuration template"

type = "storage"

[files]
base_type = "object"
required  = false

[original_filenames]
base_type = "object"
required  = false

[file_sizes]
base_type = "object"
required  = false

[added_at]
base_type  = "string"
required   = false
validation = { datetime = true }

[checksums]
base_type = "object"
required  = false
