[package]
name                 = "learnerd"
version              = "0.1.0"
edition.workspace    = true
description          = "A simple daemon for learning stuff"
authors.workspace    = true
repository.workspace = true
license.workspace    = true
readme               = "README.md"
keywords.workspace   = true

[dependencies]
learner = { path = "../learner" }
clap    = { workspace = true }
tokio   = { workspace = true }
sqlx    = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
