[package]
authors.workspace    = true
description          = "A simple daemon for learning stuff"
edition.workspace    = true
keywords.workspace   = true
license.workspace    = true
name                 = "learnerd"
readme               = "README.md"
repository.workspace = true
version              = "0.1.0"
