[package]
name        = "learnerd"
version     = "0.1.0"
edition     = "2021"
description = "A simple daemon for learning stuff"
authors     = ["Colin Roberts"]
repository  = "https://github.com/autoparallel/learner"
license     = "Apache-2.0"
# documentation = "https://docs.rs/learnerd"
readme   = "README.md"
keywords = ["learning", "research", "automation", "papers"]
