name              = "arxiv"
base_url          = "http://export.arxiv.org"
source            = "arxiv"
pattern           = "(?:^|https?://arxiv\\.org/(?:abs|pdf)/)(\\d{4}\\.\\d{4,5}|[a-zA-Z]+\\.[A-Z]{2}/\\d{7})(?:\\.pdf)?$"
endpoint_template = "http://export.arxiv.org/api/query?id_list={identifier}&max_results=1"

[response_format]
type             = "xml"
strip_namespaces = true

[response_format.field_maps.title]
path = "feed/entry/title"

[response_format.field_maps.abstract]
path = "feed/entry/summary"

[response_format.field_maps.authors]
path = "feed/entry/author/name"

[response_format.field_maps.publication_date]
path = "feed/entry/published"

[response_format.field_maps.pdf_url]
path = "feed/entry/id"

[response_format.field_maps.pdf_url.transform]
type        = "Replace"
pattern     = "/abs/"
replacement = "/pdf/"

[headers]
Accept = "application/xml"
