name = "iacr"

description = "Retriever template for getting a paper from IACR"

resource_template  = "paper"
retrieval_template = "retrieval"

base_url          = "https://eprint.iacr.org"
endpoint_template = "https://eprint.iacr.org/oai?verb=GetRecord&identifier=oai:eprint.iacr.org:{identifier}&metadataPrefix=oai_dc"
pattern           = "(?:^|https?://eprint\\.iacr\\.org/)(\\d{4}/\\d+)(?:\\.pdf)?$"
source            = "iacr"

[response_format]
clean_content    = true
strip_namespaces = true
type             = "xml"

[resource_mappings]
abstract = "OAI-PMH/GetRecord/record/metadata/dc/description"
title    = "OAI-PMH/GetRecord/record/metadata/dc/title"

[resource_mappings.authors]
from = "OAI-PMH/GetRecord/record/metadata/dc/creator"
map  = { name = "." }

[resource_mappings.publication_dates]
map = { created = "OAI-PMH/GetRecord/record/metadata/dc/date" }

[retrieval_mappings.urls]
from = "OAI-PMH/GetRecord/record/metadata/dc/identifier"
[retrieval_mappings.urls.map]
document = { paths = [
    ".",
], transform = "replace:.*/(\\d{4}/\\d+)$:https://eprint.iacr.org/$1.pdf" }
html = { paths = [
    ".",
], transform = "replace:.*/(\\d{4}/\\d+)$:https://eprint.iacr.org/$1" }


[headers]
Accept = "application/xml"
