type_name = "book"

description = "A published book, including textbooks, monographs, and edited volumes"

[[fields]]
description = "The book's full title"
field_type  = "string"
name        = "title"
required    = true
validation  = { min_length = 1, max_length = 500 }

[[fields]]
description = "The book's authors"
field_type  = "array"
name        = "authors"
required    = false

[[fields]]
description = "The book's editors, if any"
field_type  = "array"
name        = "editors"
required    = false

[[fields]]
description = "International Standard Book Number"
field_type  = "string"
name        = "isbn"
required    = false
validation  = { pattern = '''^(?:978|979)?[- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9X]$''' }

[[fields]]
description = "The book's publisher"
field_type  = "string"
name        = "publisher"
required    = false

[[fields]]
description = "When the book was published"
field_type  = "datetime"
name        = "publication_date"
required    = false

[[fields]]
description = "The edition number or description"
field_type  = "string"
name        = "edition"
required    = false

[[fields]]
description = "Total number of pages"
field_type  = "integer"
name        = "pages"
required    = false

[[fields]]
default     = "en"
description = "The book's primary language"
field_type  = "string"
name        = "language"
required    = false

[[fields]]
description = "Subject categories or classifications"
field_type  = "array"
name        = "subjects"
required    = false

[[fields]]
description = "Book summary or description"
field_type  = "string"
name        = "summary"
required    = false
