name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"  

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install Rust
        uses: dtolnay/rust-toolchain@nightly  
        with:
          components: rustfmt

      - name: install taplo
        run: cargo install taplo-cli 

      - name: run Rust fmt
        run: cargo fmt --all -- --check

      - name: run TOML fmt
        run: taplo fmt --check

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: run clippy
        run: cargo clippy --all-targets --all-features

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose --workspace

      - name: Run tests
        run: cargo test --verbose --workspace

  udeps:
    name: unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly 

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-udeps
        run: cargo install cargo-udeps --locked

      - name: Check unused dependencies
        run: cargo udeps --workspace

  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@cargo-semver-checks

      - name: Run semver checks
        run: cargo semver-checks check-release --workspace