name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@cargo-semver-checks

      - name: Run semver checks
        run: cargo semver-checks check-release --workspace

      - name: Update Cargo.lock
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Cargo.lock"
          file_pattern: "Cargo.lock"

      # Dry run for PRs
      - name: Run release-plz (dry run)
        if: github.event_name == 'pull_request'
        uses: MarcoIeni/release-plz-action@v0.5.41
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PLZ_DRY_RUN: true

      # Real release for main
      - name: Run release-plz
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: MarcoIeni/release-plz-action@v0.5.41
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}